# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [0]:
import tensorflow as tf

In [3]:
import tensorflow as tf
print(tf.__version__)

2.1.0-rc1


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [5]:
from sklearn import datasets
import matplotlib.pyplot as plt
iris =datasets.load_iris()
type(iris)

sklearn.utils.Bunch

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
X = iris.data
y = iris.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state = 42)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train, 3)
y_test = to_categorical(y_test, 3)



## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
model = tf.keras.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten

model.add(Dense(4, activation = 'relu', input_shape = (4,)))
model.add(Dense(3, activation = 'softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
model.compile(optimizer = 'sgd', loss = 'categorical_crossentropy', metrics = ['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 20        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 15        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [13]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs = 100)
#we can test at higher epochs to test the model

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 0s 4ms/sample - loss: 1.5993 - accuracy: 0.3393 - val_loss: 1.3879 - val_accuracy: 0.3158
Epoch 2/100
112/112 [==============================] - 0s 167us/sample - loss: 1.4057 - accuracy: 0.3393 - val_loss: 1.2726 - val_accuracy: 0.3158
Epoch 3/100
112/112 [==============================] - 0s 200us/sample - loss: 1.2919 - accuracy: 0.3393 - val_loss: 1.1974 - val_accuracy: 0.3158
Epoch 4/100
112/112 [==============================] - 0s 197us/sample - loss: 1.2145 - accuracy: 0.3393 - val_loss: 1.1501 - val_accuracy: 0.3158
Epoch 5/100
112/112 [==============================] - 0s 186us/sample - loss: 1.1667 - accuracy: 0.3393 - val_loss: 1.1250 - val_accuracy: 0.3158
Epoch 6/100
112/112 [==============================] - 0s 199us/sample - loss: 1.1366 - accuracy: 0.3393 - val_loss: 1.1036 - val_accuracy: 0.3158
Epoch 7/100
112/112 [==============================] - 0s 191us/sample - lo

## Question 10

### Make predictions
- Predict labels on one row

In [14]:
model.predict(X_test[0:1])

array([[0.10637728, 0.38737065, 0.50625205]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [15]:
y_test[0:1]

array([[0., 1., 0.]], dtype=float32)



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [17]:
import tensorflow as tf
print(tf.__version__)

2.1.0-rc1


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [19]:
# run this cell to upload file if you are using google colab
#from google.colab import files
#files.upload()     #I am not using it as this is taking more time than expected.
from google.colab import drive
drive.mount('/gdrive')


Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).


In [0]:
import pandas as pd
data = pd.read_csv('/gdrive/My Drive/GL_Colab/20200126/prices.csv')

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
data.drop(['date','symbol'], axis=1, inplace=True)

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [0]:
df = data.loc[:1000,:]

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
X = df[['open','close','low', 'high']]
y = df['volume']/1000000

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
import numpy as np

X = np.array(X).astype('float32')
y = np.array(y).astype('float32')

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [25]:

X = tf.math.l2_normalize(X)
X

<tf.Tensor: shape=(1001, 4), dtype=float32, numpy=
array([[0.0220257 , 0.02245575, 0.02182584, 0.02252892],
       [0.02234869, 0.02141006, 0.02140292, 0.02240222],
       [0.02076765, 0.02051247, 0.0205089 , 0.02136723],
       ...,
       [0.00785166, 0.00799442, 0.00780705, 0.00799621],
       [0.00643836, 0.00662752, 0.00642587, 0.00664358],
       [0.00861185, 0.00858686, 0.00846195, 0.00863326]], dtype=float32)>

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
W = tf.zeros(shape=(4, 1))
b = tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
@tf.function
def prediction(features, W, b):
      y_pred = tf.add(tf.matmul(features, W), b)
      return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
@tf.function
def loss(y_actual, y_predicted):
      diff = y_actual - y_predicted
      sqr = tf.square(diff)
      avg = tf.reduce_mean(sqr)
      return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(x, y_actual, w, b, learning_rate=0.01):
# Record mathematical operations on 'tape' to calculate loss 
  with tf.GradientTape() as t: 
    t.watch([w,b]) 
    current_prediction = prediction(x, w, b)
    current_loss = loss(y_actual, current_prediction)

# Calculate Gradients for Loss with respect to Weights and Bias 
  dw, db = t.gradient(current_loss,[w, b]) 

# Update Weights and Bias 
  w = w - learning_rate * dw
  b = b - learning_rate * db 

  return w,b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [30]:
for i in range(100):    
    
    W, b = train(X, y, W, b)
    print('Current Training Loss on iteration', i, loss(y, prediction(X, W, b)).numpy())

Current Training Loss on iteration 0 235.93304
Current Training Loss on iteration 1 234.86021
Current Training Loss on iteration 2 233.83003
Current Training Loss on iteration 3 232.8406
Current Training Loss on iteration 4 231.89032
Current Training Loss on iteration 5 230.97789
Current Training Loss on iteration 6 230.10149
Current Training Loss on iteration 7 229.25984
Current Training Loss on iteration 8 228.45142
Current Training Loss on iteration 9 227.67511
Current Training Loss on iteration 10 226.92967
Current Training Loss on iteration 11 226.21361
Current Training Loss on iteration 12 225.52605
Current Training Loss on iteration 13 224.86557
Current Training Loss on iteration 14 224.23131
Current Training Loss on iteration 15 223.62231
Current Training Loss on iteration 16 223.03731
Current Training Loss on iteration 17 222.47556
Current Training Loss on iteration 18 221.9361
Current Training Loss on iteration 19 221.41794
Current Training Loss on iteration 20 220.92036
Curr

### Observe values of Weight
- Print the updated values

In [31]:
print('Weights:', W)

Weights: tf.Tensor(
[[0.05471141]
 [0.05481017]
 [0.05415636]
 [0.05525874]], shape=(4, 1), dtype=float32)


### Observe values of Bias
- Print the updated values

In [32]:
print('Bias:',b)

Bias: tf.Tensor([4.6035933], shape=(1,), dtype=float32)
